services:
  - type: web
    name: sentiment-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn sentiment_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sentiment-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: sentiment_api.settings.production
      - key: PYTHON_VERSION
        value: 3.10.6
    plan: free
    healthCheckPath: /api/health/

databases:
  - name: sentiment-db
    plan: free
    databaseName: sentimentdb
    user: sentimentuser
